# configs/data.yaml

interval: "5m"
start_date: "2025-01-01"

tables:
    bronze_market:
        "path": "/opt/app/delta/bronze/market/"
        "partition_by": ["symbol", "date"]

    silver_market:
        "path": "/opt/app/delta/silver/market/"
        "partition_by": ["symbol", "date"]

    gold_market:
        "path": "/opt/app/delta/gold/market/"
        "partition_by": ["symbol", "date"]

    market_batch_state:
        "path": "/opt/app/delta/state/market_batch/"

    market_stream_state:
        "path": "/opt/app/delta/state/market_stream/"

    predictions_log_return_lead1:
        "path": "/opt/app/delta/predictions/log_return_lead1/"
        "partition_by": ["symbol", "date"]

    predictions_log_return_lead1_state:
        "path": "/opt/app/delta/state/predictions/log_return_lead1/"

raw_data_path:
    market: "/opt/app/delta/raw_data/market/"

checkpoints:
    market: "/opt/app/delta/checkpoints/market/"
    predictions_log_return_lead1: "/opt/app/delta/checkpoints/predictions/log_return_lead1/"


symbols: ["BTCUSDT", "ETHUSDT"]
# , "BNBUSDT", "SOLUSDT", "XRPUSDT", "USDCUSDT"


render_uri:
    market_live: "wss://cryptoquantproducer.onrender.com/ws/binance/live"
    market_today: "https://cryptoquantproducer.onrender.com/binance/backfill"