# configs/data.yaml

interval: "5m"
start_date: "2026-01-01"

tables:
    bronze_market:
        path: "/opt/app/delta/bronze/market/"
        partition_by: ["symbol", "date"]
        checkpoint: "/opt/app/delta/checkpoint/bronze/market/"

    silver_market:
        path: "/opt/app/delta/silver/market/"
        partition_by: ["symbol", "date"]
        checkpoint: "/opt/app/delta/checkpoint/silver/market/"

    gold_market:
        path: "/opt/app/delta/gold/market/"
        partition_by: ["symbol", "date"]
        checkpoint: "/opt/app/delta/checkpoint/gold/market/"

    market_state:
        path: "/opt/app/delta/state/market/"
        partition_by: ["symbol"]

    bronze_sentiment:
        path: "/opt/app/delta/bronze/sentiment/"
        partition_by: ["source", "symbol"]
        checkpoint: "/opt/app/delta/checkpoint/bronze/sentiment/"

    silver_sentiment:
        path: "/opt/app/delta/silver/sentiment/"
        partition_by: ["source", "symbol"]
        checkpoint: "/opt/app/delta/checkpoint/silver/sentiment/"

    gold_sentiment:
        path: "/opt/app/delta/gold/sentiment/"
        partition_by: ["symbol", "window_date"]
        checkpoint: "/opt/app/delta/checkpoint/gold/sentiment/"

    bronze_streaming_sentiment:
        path: "/opt/app/delta/bronze_streaming/sentiment/"
        partition_by: ["source", "symbol"]
        checkpoint: "/opt/app/delta/checkpoint/bronze_streaming/sentiment/"

    silver_streaming_sentiment:
        path: "/opt/app/delta/silver_streaming/sentiment/"
        partition_by: ["source", "symbol"]
        checkpoint: "/opt/app/delta/checkpoint/silver_streaming/sentiment/"

    gold_streaming_sentiment:
        path: "/opt/app/delta/gold_streaming/sentiment/"
        partition_by: ["symbol", "window_date"]
        checkpoint: "/opt/app/delta/checkpoint/gold_streaming/sentiment/"

    sentiment_state:
        path: "/opt/app/delta/state/sentiment/"
        partition_by: ["layer", "source", "symbol", "state_date"]

raw_data_path:
    market: "/opt/app/delta/raw_data/market/"

symbols: ["BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "XRPUSDT", "USDCUSDT"]


render_uri:
    market_live: "wss://cryptoquantproducer.onrender.com/ws/binance/live"
    market_today: "https://cryptoquantproducer.onrender.com/binance/backfill"