# configs/spark.yaml

app_name: CryptoQuant

master: local[2]

spark_configs:
  # Delta Lake
  spark.sql.extensions: io.delta.sql.DeltaSparkSessionExtension
  spark.sql.catalog.spark_catalog: org.apache.spark.sql.delta.catalog.DeltaCatalog

  # Performance (local optimized)
  spark.sql.shuffle.partitions: 4
  spark.default.parallelism: 4

  # Memory
  spark.driver.memory: 1g
  spark.executor.memory: 1g
  spark.driver.maxResultSize: 512m

  spark.executor.memoryOverhead: 256m
  spark.driver.memoryOverhead: 256m


  # Adaptive Query Execution
  spark.sql.adaptive.enabled: true
  spark.sql.adaptive.coalescePartitions.enabled: true
  spark.sql.adaptive.shuffle.targetPostShuffleInputSize: 32MB

  # Storage
  spark.sql.warehouse.dir: /tmp/spark-warehouse

  # Arrow (faster pandas ↔ spark)
  spark.sql.execution.arrow.pyspark.enabled: true

  # Logging / Debugging
  spark.ui.enabled: false