"""create market table

Revision ID: 1ea7c5eda3d2
Revises: 
Create Date: 2026-04-21 13:18:59.554588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ea7c5eda3d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market',
    sa.Column('open_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('open', sa.Double(), nullable=True),
    sa.Column('high', sa.Double(), nullable=True),
    sa.Column('low', sa.Double(), nullable=True),
    sa.Column('close', sa.Double(), nullable=True),
    sa.Column('volume', sa.Double(), nullable=True),
    sa.Column('trades', sa.Integer(), nullable=True),
    sa.Column('taker_buy_base', sa.Double(), nullable=True),
    sa.Column('log_return', sa.Double(), nullable=True),
    sa.Column('volatility', sa.Double(), nullable=True),
    sa.Column('imbalance_ratio', sa.Double(), nullable=True),
    sa.Column('buy_ratio', sa.Double(), nullable=True),
    sa.Column('log_return_lag1', sa.Double(), nullable=True),
    sa.Column('log_return_lag2', sa.Double(), nullable=True),
    sa.Column('buy_ratio_lag1', sa.Double(), nullable=True),
    sa.Column('ma_5', sa.Double(), nullable=True),
    sa.Column('ma_20', sa.Double(), nullable=True),
    sa.Column('volatility_5', sa.Double(), nullable=True),
    sa.Column('volume_5', sa.Double(), nullable=True),
    sa.Column('buy_ratio_5', sa.Double(), nullable=True),
    sa.Column('momentum', sa.Double(), nullable=True),
    sa.Column('volume_spike', sa.Double(), nullable=True),
    sa.Column('price_range_ratio', sa.Double(), nullable=True),
    sa.Column('body_size', sa.Double(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('trend_strength', sa.Double(), nullable=True),
    sa.Column('volatility_ratio', sa.Double(), nullable=True),
    sa.Column('is_valid_feature_row', sa.Boolean(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('ingestion_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('open_time', 'symbol')
    )
    op.execute("SELECT create_hypertable('market', by_range('open_time'), if_not_exists => TRUE)")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market')
    # ### end Alembic commands ###
